module.exports = {
  DASHBOARD: ['dashboard'],
  LEAD: ['dashboard', 'leads', 'customer', 'product', 'lead_report', 'workflow'],
  TASK: ['list_task', 'create_task', 'update_task', 'delete_task'],
  SETTINGS: ['settings', 'category', 'city', 'source', 'reference', 'product', 'shift', 'leads_status', 'tags', 'customer_group', 'leave_type', 'pipeline'],
  REPORTS: ['reports', 'followup_report', 'task_report', 'leads_report', 'attendance_report', 'leave_report', 'payment_report'],
  ACCOUNTS: ['accounts'],
  CUSTOMER: ['list_customer', 'create_customer', 'update_customer', 'delete_customer'],
  TEAMMEMBER: ['list_teammember', 'create_teammember', 'update_teammember', 'delete_teammember'],
  ATTENDANCE: ['attendance'],
  LEAVE: ['list_leave', 'create_leave', 'update_leave', 'delete_leave'],
  FRANCHISE: ['list_franchise', 'create_franchise', 'update_franchise', 'delete_franchise'],
  BUSINESS: ['list_business', 'create_business', 'update_business', 'delete_business'],
  COMMUNICATION: ['list_communication', 'create_communication', 'update_communication', 'delete_communication'],
  DEPARTMENT: ['list_department', 'create_department', 'update_department', 'delete_department'],
  SALARYGENERATION: ['salary_generation'],
  SUBSCRIPTION: ['subscription'],
  TODO: ['todo_list'],
  USERPROFILE: ['user_profile'],
  BUSINESSPROFILE: ['business_profile'],
  TEMPLATE: ['whatsapp_template', 'email_template'],
};
